#!/usr/bin/env node
import assert from "node:assert/strict";
import { caevForEventType, daysOut, computeLookupVerdict, deriveVendorGroups, getScopeVendors, setScopeVendors } from "../src/lib/lookup-verdict.ts";
import { setVendorDefault } from "../src/lib/coverage-settings.ts";
const storage = (() => { const m=new Map(); return { getItem:k=>m.get(k)??null,setItem:(k,v)=>m.set(k,String(v)),removeItem:k=>m.delete(k) }; })();
const today=new Date("2026-09-01T12:00:00Z");
assert.equal(caevForEventType("cash-dividend"), "DVOP");
assert.equal(daysOut(new Date("2026-09-03"), today), 2);
assert.equal(getScopeVendors(storage).length, 7, "unset scope defaults to every vendor");
setScopeVendors(["msci"], storage);
assert.deepEqual(getScopeVendors(storage), ["msci"], "a persisted scope narrows the roster");
setScopeVendors([], storage);
assert.equal(getScopeVendors(storage).length, 7, "an empty scope is never persisted as 0 vendors forever");
storage.setItem("ca-hub.vendor-scope.v1", "not json");
assert.equal(getScopeVendors(storage).length, 7, "corrupt storage falls back to the default roster");
setScopeVendors(["msci", "ftse"], storage);
setVendorDefault("ftse", 5, storage);
const checkedAbsent={state:"absent", checkedAt:today.toISOString()};
const verdict=ex=>computeLookupVerdict({ticker:"ABC",eventType:"cash-dividend",exDate:new Date(ex),today,storage,scope:getScopeVendors(storage),getConfirmation:v=>v==="ftse"?checkedAbsent:null,isPresentAtVendor:()=>false});
const early=deriveVendorGroups(verdict("2026-09-10"));
assert.deepEqual(early.expectedAbsent, []);
assert.equal(early.notYetDue.some(r=>r.vendor==="ftse"), true);
const boundary=verdict("2026-09-06");
assert.equal(boundary.rows.length, 2, "narrowed scope excludes vendors from the verdict entirely, not just from display");
assert.deepEqual(deriveVendorGroups(boundary).expectedAbsent.map(r=>r.vendor), ["ftse"]);
console.log("OK — lookup primitives, persisted scope narrowing, two groups, and horizon boundary pass");
